# Deployment definition for the 'api-deployment' within the 'cdss' namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: climateqa # Namespace where the Deployment is located
  name: qdrant-deployment # Name of the Deployment resource
  labels: # List of labels to give context on that deployment
    name: qdrant
    io.kompose.service: qdrant
    type: qdrant
spec:
  replicas: 1 # Number of desired replicas (pods) for this Deployment
  selector:
    matchLabels:
      app: qdrant # Selects pods with the label 'app: qdrant'
  template:
    metadata:
      labels:
        app: qdrant # Label 'app' with value 'qdrant' applied to the pod template
    spec:
      containers:
        - name: qdrant # Name of the container within the pod
          image: qdrant/qdrant:latest # Docker image to use for the container
          ports:
            - containerPort: 6333 # Port to expose on the container
          envFrom:
            # Environment variables to be sourced from ConfigMaps and Secrets
            - configMapRef:
                name: configmap-qdrant # ConfigMap named 'configmap-api' will be used as an environment source