# Secret definition for the 'secrets-worker' within the 'climateqa' namespace
apiVersion: v1
kind: Secret
metadata:
  namespace: climateqa # Namespace where the Secret is located
  name: secrets-qa # Name of the Secret resource
type: Opaque # Specifies the type of the Secret. In this case, it is an opaque Secret.
stringData:
  BLOB_ACCOUNT_NAME: ekitrnfrsbxadl01
  BLOB_ACCOUNT_KEY: BcxKmF2mClzit2fXORy6qhlrnJQgZcdKV9F0Hiya0CeH4Nz0YyNNF9zqwlVg04vt9f+ZluuDGX4h+AStiOFZwQ==
  BLOB_ACCOUNT_URL: https://ekiinofrsbxadl01data.file.core.windows.net/climategpt
  GRADIO_ENV: local
  AZURE_OPENAI_API_BASE_URL: https://francecentral.api.cognitive.microsoft.com/
  AZURE_OPENAI_API_VERSION: 2023-07-01-preview
  AZURE_OPENAI_API_DEPLOYMENT_NAME: icade
  AZURE_OPENAI_API_KEY: ee2b8615849f43f29f15fe54e787d5eb
  HUGGINGFACE_API_KEY: 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
  OPENAI_API_KEY: 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
  PINECONE_API_KEY: 1e408fa7-0456-4378-af33-48cc5632db46
  PINECONE_API_ENVIRONMENT: gcp-starter
  PINECONE_API_INDEX: climateqa
  RETRIEVER_API_ENDPOINT: https://ekiinofr-sbx-func-01-climate-ai.azurewebsites.net/api/retrieve
  RETRIEVER_API_KEY: ccW05xmeDbZ5shrtjKArUUfCSiuVtN-G_VSwDQAOpiH2AzFuyYG1IA==
  QDRANT_HOST:  http://qdrant-service:6333