# Service definition for the 'api-service' within the 'cdss' namespace
apiVersion: v1
kind: Service
metadata:
  namespace: climateqa
  labels:
    io.kompose.service: qa
  name: qa-service
spec:
  selector:
    app: qa
  type: NodePort # Exposes the service internally within the cluster only
  ports:
    - protocol: TCP
      port: 80 # Exposed port on the ClusterIP
      targetPort: 7860 # Traffic will be forwarded to port 8080 of the selected pods
      nodePort: 30007